"""Generate a KPvK bitbase from syzygy, emit it as a packed C header.

The full tablebase port is 1600 lines with 51 Stockfish-internal dependencies
and a failure mode (a subtly wrong prober returning confidently wrong scores)
that makes it a fresh-session job. KPvK is the completable subset: king and pawn
against king is the single most common ending, and its whole state space is
64 x 64 x 48 x 2 = 393,216 positions, which packs into 48KB of bits.

Correct by construction: every entry is read from the syzygy tables already on
this box via python-chess, so there is no format parsing to get wrong. The
validation step this replaces -- probe against python-chess on tens of thousands
of positions -- is instead the generation step itself.

It is used in the SEARCH, not the evaluation. A node that is exactly KPvK
returns the exact score directly, the same shape as contempt: a search-side
value, not an eval term. So no concept, weight or PST changes and eval_check
must remain 0.000000. Putting it in the eval instead would break the
C-equals-Python invariant unless the Python eval learned it too.

Index: [stm][wk][bk][pawn_index], pawn_index 0..47 for squares a2..h7 (a pawn
cannot stand on rank 1 or 8). White is the side with the pawn; the caller
mirrors when Black has it.

Only WIN vs NOT-WIN is stored. KPvK has no losses for the pawn side, so one bit
per position is exact rather than a lossy compression.
"""
import pathlib
import sys

import chess
import chess.syzygy

TB = pathlib.Path.home() / "syzygy345"
OUT = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else pathlib.Path("core/kpk_data.h")

bits = bytearray((2 * 64 * 64 * 48 + 7) // 8)
wins = 0
total = 0
illegal = 0

with chess.syzygy.open_tablebase(str(TB)) as tb:
    for stm in (0, 1):                      # 0 = white (pawn side) to move
        for wk in range(64):
            for bk in range(64):
                if wk == bk:
                    continue
                for pi in range(48):
                    psq = pi + 8           # a2..h7
                    if psq == wk or psq == bk:
                        continue
                    b = chess.Board(None)
                    b.set_piece_at(wk, chess.Piece(chess.KING, chess.WHITE))
                    b.set_piece_at(bk, chess.Piece(chess.KING, chess.BLACK))
                    b.set_piece_at(psq, chess.Piece(chess.PAWN, chess.WHITE))
                    b.turn = chess.WHITE if stm == 0 else chess.BLACK
                    if not b.is_valid():
                        illegal += 1
                        continue
                    total += 1
                    try:
                        wdl = tb.probe_wdl(b)
                    except (chess.syzygy.MissingTableError, KeyError):
                        continue
                    # wdl is from the side to move; a win for the PAWN side is
                    # wdl > 0 when white moves, wdl < 0 when black moves.
                    win = (wdl > 0) if stm == 0 else (wdl < 0)
                    if win:
                        idx = ((stm * 64 + wk) * 64 + bk) * 48 + pi
                        bits[idx >> 3] |= 1 << (idx & 7)
                        wins += 1

lines = []
for i in range(0, len(bits), 16):
    lines.append("    " + ",".join(f"0x{b:02x}" for b in bits[i:i + 16]) + ",")

OUT.write_text(
    "/* KPvK bitbase, generated by research/gen_kpk.py from the syzygy tables.\n"
    " * Correct by construction: every bit is read from syzygy, so there is no\n"
    " * table format parsing here to get wrong.\n"
    " * Index: ((stm*64 + wk)*64 + bk)*48 + (pawn_square - 8), one bit per\n"
    " * position, set = WIN for the pawn side. KPvK has no losses for the pawn\n"
    " * side, so one bit is exact rather than a lossy encoding.\n"
    f" * {wins:,} wins of {total:,} legal positions. DO NOT HAND-EDIT. */\n"
    "static const unsigned char KPK_BITS[] = {\n" + "\n".join(lines) + "\n};\n")

print(f"{total:,} legal positions, {wins:,} wins, {illegal:,} illegal skipped")
print(f"wrote {OUT} ({len(bits):,} bytes of bitbase)")
