"""Tactics regression gate.

Runs the Stockfish-verified suite (tests/suites/tactics_v1.epd, generated by
research/make_suite.py). The threshold is set just below the measured baseline;
if an engine change drops accuracy below it, the change is a regression.

Baseline (2026-07-13, 1.0s/move): see research/baselines.json.
"""

from pathlib import Path

import pytest

from research.tactics import run_suite

SUITE = Path(__file__).parent / "suites" / "tactics_v1.epd"
MOVETIME = 1.0
MIN_ACCURACY_PCT = 90  # baseline 23/24 (95.8%); threshold allows one extra miss


@pytest.mark.slow
def test_tactics_suite():
    result = run_suite(SUITE, movetime=MOVETIME, verbose=False)
    assert result["pct"] >= MIN_ACCURACY_PCT, (
        f"tactics accuracy regressed: {result['solved']}/{result['total']} "
        f"({result['pct']:.1f}%) < {MIN_ACCURACY_PCT}%")
